export enum EditType {
  Checkbox = 'Checkbox',
  TextArea = 'TextArea',
  Date = 'Date',
  Wysiwyg = 'Wysiwyg',
  Image = 'Image',
  Input = 'Input',
  File = 'File',
  Select = 'Select',
  Repeater = 'Repeater',
  RadioButtons = 'RadioButtons',
  RangeSlider = 'RangeSlider',
  Row = 'Row',
  Autocomplete = 'Autocomplete',
  AutocompleteMultiple = 'AutocompleteMultiple',
  Icon = 'Icon',
  ButtonToggle = 'ButtonToggle',
}
