export const formDataExample = {
  uniqueNumber: 'D2020-00003H-00000A',
  registrationPointType: 'WELCOME_CENTER',
  locationId: 55,
  firstName: 'SDFDSF',
  name: 'DSFDSF',
  dateOfBirth: '2020-09-03',
  age: null,
  gender: null,
  ageRange: 'NONE',
  involvement: 'RELATED',
  facilityKindType: null,
  triage: null,
  preTriage: null,
  preTriageHistory: [],
  triageHistory: [],
  nationalities: [],
  languages: [],
  nationalRegistrationNumber: null,
  contactNumbers: [],
  email: [],
  incidentIds: [5],
  temporaryResidence: null,
  temporaryOvernightStay: null,
  searchedBy: [],
  lookingFor: [],
  patientTransfers: [
    {
      id: 150,
      destinationId: 55,
      registrationPointType: 'WELCOME_CENTER',
      creationTime: '2020-09-17T14:25:49.094792+02:00',
      actualDepartureTime: null,
      actualArrivalTime: '2020-09-17T14:25:48.71+02:00',
      departureTimeToNextDestination: null,
    },
  ],
  searchRequests: [
    {
      id: 24,
      dossierUniqueNumber: 'D2020-00003H-00000A',
      linkedDossiers: [
        {
          uniqueNumber: 'D2020-00003H-000007',
          firstName: 'TEST',
          name: 'THIS',
          dateOfBirth: '2020-09-17',
          involvement: 'VICTIM',
          contactNumber: null,
        },
      ],
      uniqueNumber: 'D2020-00003H-000007',
      name: null,
      firstName: null,
      involvement: null,
      dateOfBirth: null,
      gender: null,
      phoneNumber: null,
      nationalities: [],
      relationship: 'PARENT',
      lookingFor: null,
      freeText: 'test',
    },
    {
      id: 25,
      dossierUniqueNumber: 'D2020-00003H-00000A',
      linkedDossiers: [
        {
          uniqueNumber: 'D2020-00003H-000005',
          firstName: 'SDFDSF',
          name: 'DSF',
          dateOfBirth: '2020-09-01',
          involvement: 'VICTIM',
          contactNumber: null,
        },
      ],
      uniqueNumber: 'D2020-00003H-000005',
      name: null,
      firstName: null,
      involvement: null,
      dateOfBirth: null,
      gender: null,
      phoneNumber: null,
      nationalities: [],
      relationship: 'FAMILY',
      lookingFor: null,
      freeText: 'dsfdsfdsf',
    },
    {
      id: 26,
      dossierUniqueNumber: 'D2020-00003H-00000A',
      linkedDossiers: [
        {
          uniqueNumber: 'D2020-00003H-000005',
          firstName: 'SDFDSF',
          name: 'DSF',
          dateOfBirth: '2020-09-01',
          involvement: 'VICTIM',
          contactNumber: null,
        },
      ],
      uniqueNumber: 'D2020-00003H-000005',
      name: null,
      firstName: null,
      involvement: null,
      dateOfBirth: null,
      gender: null,
      phoneNumber: null,
      nationalities: [],
      relationship: 'SIBLING',
      lookingFor: null,
      freeText: 'test',
    },
    {
      id: 27,
      dossierUniqueNumber: 'D2020-00003H-00000A',
      linkedDossiers: [
        {
          uniqueNumber: 'D2020-00003H-000007',
          firstName: 'TEST',
          name: 'THIS',
          dateOfBirth: '2020-09-17',
          involvement: 'VICTIM',
          contactNumber: null,
        },
      ],
      uniqueNumber: 'D2020-00003H-000007',
      name: null,
      firstName: null,
      involvement: null,
      dateOfBirth: null,
      gender: null,
      phoneNumber: null,
      nationalities: [],
      relationship: 'SIBLING',
      lookingFor: null,
      freeText: 'test',
    },
  ],
  contactMoment: [],
  text: null,
  address: null,
  creationTime: null,
  locations: null,
};
